/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testroti;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import testroti.formBarang;



/**
 *
 * @author Lenovo
 */
public class supplier extends javax.swing.JFrame {

    /**
     * Creates new form supplier
     */
    
    public supplier() {
        initComponents();
        this.setResizable(false);
        load_table();
        kosong();
        autonumber();
        }
    
        /*
    private void tanggal(){
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                waktu.setText(new SimpleDateFormat("EEEE dd MMMM yyyy hh:mm:ss").format(new java.util.Date()));
            }
        },0,1000); 
    }
    */
    
       private void load_table() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Supplier");
        model.addColumn("Nama Supplier");
        model.addColumn("Telepon");
        model.addColumn("Alamat");
   
       try {
            int no = 1;
            String sql = "SELECT * FROM supplier";
            java.sql.Connection conn = (Connection)connect_db.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                model.addRow(new Object[]{no++, 
                    res.getString(1), 
                    res.getString(2), 
                    res.getString(3), 
                    res.getString(4)                    
                });   
            }
            jTable1.setModel(model);
            } catch (SQLException e) {            
        }
    }
    
    private void kosong() {
        txtidSupplier.setText(null);
        txtnamasupp.setText(null);
        txttelepon.setText(null);
        txtalamat.setText(null);
        autonumber();
    }
    private void autonumber() {
       try {
           String sql = "SELECT MAX(id_supp) AS ID FROM supplier";
           java.sql.Connection conn = (Connection)connect_db.configDB();
           java.sql.Statement pst = conn.createStatement();
           java.sql.ResultSet rs = pst.executeQuery(sql);
           while(rs.next()) {
               Object[] obj = new Object[1];
               obj[0] = rs.getString("ID");
               if(obj[0] == null) {
                   obj[0] = "SP00";
               }
               String str_id = (String) obj[0];
               String kd = str_id.substring(2, 5);
               int int_code = Integer.parseInt(kd);
               int_code++;
               String a = String.format("%03d", int_code);
               String b = "SP" + a;
               txtidSupplier.setText(b);
               txtidSupplier.setEditable(false);
                }
           } catch (NumberFormatException | SQLException e) {      
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtidSupplier = new javax.swing.JTextField();
        txtalamat = new javax.swing.JTextField();
        txtnamasupp = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        linkBarang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setBorder(null);
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 800, 200));

        txtidSupplier.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtidSupplier.setAlignmentX(1.0F);
        txtidSupplier.setAlignmentY(1.0F);
        txtidSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidSupplierActionPerformed(evt);
            }
        });
        getContentPane().add(txtidSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 141, 160, 35));

        txtalamat.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        getContentPane().add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 141, 160, 35));

        txtnamasupp.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        getContentPane().add(txtnamasupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 190, 160, 35));

        txttelepon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        getContentPane().add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 188, 160, 35));

        btnSimpan.setBackground(new java.awt.Color(246, 118, 73));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 80, 40));

        btnEdit.setBackground(new java.awt.Color(246, 118, 73));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 80, 40));

        btnClear.setBackground(new java.awt.Color(246, 118, 73));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 80, 40));

        btnHapus.setBackground(new java.awt.Color(246, 118, 73));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 280, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Suppliernb.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 770));

        linkBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkBarangActionPerformed(evt);
            }
        });
        getContentPane().add(linkBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void txtidSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidSupplierActionPerformed
        txtidSupplier.setVisible(true);       
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidSupplierActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            String sql = "INSERT INTO supplier VALUES ('" + txtidSupplier.getText() +  "','" + txtnamasupp.getText()
                    + "','" + txttelepon.getText() + "','" + txtalamat.getText() + "')";
            java.sql.Connection conn = (Connection) connect_db.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Supplier Berhasil Di Tambahkan");          
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        load_table();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
            try {
            String sql = "UPDATE supplier SET nama_supp = '"+txtnamasupp.getText() 
                    +"',alamat = '"+txtalamat.getText()+"',telp_supp = '"+txttelepon.getText()+
                    "'WHERE id_supp ='"+txtidSupplier.getText()+"'";
            java.sql.Connection conn = (Connection)connect_db.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Perbarui");
            
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal!!"+e.getMessage());
        }
        load_table();
        kosong();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int pop = JOptionPane.showConfirmDialog(this, "Yakin kah dek?", "Hapus", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pop == JOptionPane.YES_OPTION) {                
            
        try {
            String sql = "DELETE FROM supplier WHERE id_supp = '"+txtidSupplier.getText()+"'";
            java.sql.Connection conn = (Connection)connect_db.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int row = jTable1.getSelectedRow();
            model.removeRow(row);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        load_table();
        kosong();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String kode_barang = jTable1.getValueAt(baris, 1).toString();
        txtidSupplier.setText(kode_barang);
        
        if (jTable1.getValueAt(baris, 2)==null) {
            txtnamasupp.setText("");
        } else {
            txtnamasupp.setText(jTable1.getValueAt(baris, 2).toString());
        }
        if (jTable1.getValueAt(baris, 3)==null) {
            txttelepon.setText("");
        } else {
            txttelepon.setText(jTable1.getValueAt(baris, 3).toString());
        }
        if (jTable1.getValueAt(baris, 4)==null) {
            txtalamat.setText("");
        } else {
            txtalamat.setText(jTable1.getValueAt(baris, 4).toString());
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void linkBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkBarangActionPerformed
        setVisible(false);
        new formBarang().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_linkBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new supplier().setVisible(true);
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton linkBarang;
    private javax.swing.JTextField txtalamat;
    private javax.swing.JTextField txtidSupplier;
    private javax.swing.JTextField txtnamasupp;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables

}
    
